import { Product } from "../interfaces/barcode-products.interface";

export const products: Product[] = [
  {
    barcode_number: "885926323828",
    barcode_formats: "UPC-A 885926323828, EAN-13 0885926323828",
    mpn: "TIIP7-MARB-WT",
    model: "",
    asin: "B079L4WR4T",
    title: "Apple TIIP7-MARB-WT iPhone 8 & 7 Marble IMD Soft TPU Case, White",
    category: "Electronics > Communications > Telephony > Mobile Phone Accessories > Mobile Phone Cases",
    manufacturer: "Samsung",
    brand: "Apple Inc",
    contributors: [],
    age_group: "",
    ingredients: "",
    nutrition_facts: "",
    energy_efficiency_class: "",
    color: "white",
    gender: "",
    material: "",
    pattern: "",
    format: "",
    multipack: "",
    size: "",
    length: "",
    width: "",
    height: "",
    weight: "5.85lb",
    release_date: "",
    description: "iPhone 8 & 7 Marble IMD Soft TPU Case. Features   Made of premium quality TPU material, this protective case offers superior durability for an extra-long service life; It is specially designed for bump and shock absorption and protection of your iPhone from accidental scratches; The excellent cutout allows easy access to all ports such as camera, earphone jack, speaker; The simple yet elegant irregular patterns in a white tone adds a touch of style to this protective case; Improved craftsmanship makes this case deliver a soft and natural texture; This protective case is easy to install and remove without adding any bulk or damage to your iPhone;  Specifications    Color:  White;  Material:  TPU;  Weight:  0.05 lbs; .",
    features: [],
    images: [
      "https://images.barcodelookup.com/2123/21231886-1.jpg"
    ],
    last_update: "2022-01-05 08:52:02",
    stores: [
      {
        name: "LivingSocial",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "8.99",
        sale_price: "7.88",
        tax: [],
        link: "https://www.livingsocial.com/deals/gg-cm-soft-protective-cover-with-marble-print-for-iphone-and-samsung-models?deal_option=f31dc838-4857-4d80-91a6-d9c9a7ee05fa&z=",
        item_group_id: "",
        availability: "",
        condition: "",
        shipping: [],
        last_update: "2021-06-22 02:47:25"
      },
      {
        name: "Overstock.com",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "10.98",
        sale_price: "9.99",
        tax: [],
        link: "https://www.overstock.com/14559720/product.html?TRACK=affcjfeed&CID=207442&fp=F",
        item_group_id: "",
        availability: "",
        condition: "",
        shipping: [],
        last_update: "2021-06-22 04:38:41"
      },
      {
        name: "Groupon",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "9.99",
        sale_price: "",
        tax: [],
        link: "https://rd.bizrate.com/rd?t=https://www.groupon.com/deals/gg-cm-soft-protective-cover-with-marble-print-for-iphone-and-samsung-models?deal_option=f31dc838-4857-4d80-91a6-d9c9a7ee05fa&tsToken%",
        item_group_id: "",
        availability: "in stock",
        condition: "",
        shipping: [],
        last_update: "2021-06-22 05:28:12"
      },
      {
        name: "UnbeatableSale.com",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "22.25",
        sale_price: "12.25",
        tax: [],
        link: "http://www.technooutlet.com/drmw8344.html",
        item_group_id: "",
        availability: "in stock",
        condition: "new",
        shipping: [
          {
            country: "US",
            region: "",
            service: "",
            price: "10.94 USD"
          }
        ],
        last_update: "2022-01-05 08:52:02"
      }
    ],
    reviews: []
  },
  {
    barcode_number: "887276119090",
    barcode_formats: "UPC-A 887276119090, EAN-13 0887276119090",
    mpn: "LH65EDEPLGC",
    model: "",
    asin: "",
    title: "Samsung ED-E Series LH65EDEPLGC ED65E 65-inch Direct-Lit LED Monitor - 1080p (Full HD) - 4000:1 - 6ms - HDMI, D-SUB, DVI-D",
    category: "Electronics > Video > Computer Monitors",
    manufacturer: "SAMSUNG",
    brand: "",
    contributors: [],
    age_group: "",
    ingredients: "",
    nutrition_facts: "",
    energy_efficiency_class: "",
    color: "",
    gender: "",
    material: "",
    pattern: "",
    format: "",
    multipack: "",
    size: "",
    length: "",
    width: "",
    height: "",
    weight: "",
    release_date: "",
    description: "Samsung ED-E Series LH65EDEPLGC ED65E 65-inch Direct-Lit LED Monitor - 1080p (Full HD) - 4000:1 - 6ms - HDMI, D-SUB, DVI-D.",
    features: [],
    images: [
      "https://images.barcodelookup.com/1427/14273900-1.jpg"
    ],
    last_update: "2021-06-22 03:49:05",
    stores: [
      {
        name: "Tech For Less",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "1.00",
        sale_price: "",
        tax: [],
        link: "http://www.techforless.com/cgi-bin/tech4less/LH65EDEPLGC?mv_pc=cj_feed&utm_source=cj&utm_medium=cj_feed&utm_campaign=cj",
        item_group_id: "",
        availability: "",
        condition: "",
        shipping: [],
        last_update: "2021-06-22 02:32:17"
      },
      {
        name: "Rakuten.com",
        country: "US",
        currency: "USD",
        currency_symbol: "$",
        price: "1536.97",
        sale_price: "",
        tax: [],
        link: "https://www.rakuten.com/shop/tech-for-less-llc/product/LH65EDEPLGC_C7/?scid=af_feed",
        item_group_id: "",
        availability: "",
        condition: "",
        shipping: [],
        last_update: "2021-06-22 02:47:10"
      }
    ],
    reviews: []
  },
]